project:
  type: book

book:
  title: "Ingeniería de datos"
  author: "Iraitz Montalbán"
  cover-image: cover.png
  favicon: cover.png
  site-url: https://iraitzm.github.io/ingenieria-datos/
  repo-url: https://github.com/IraitzM/ingenieria-datos
  date: today
  page-navigation: true
  search: true
  sharing: [linkedin]
  sidebar:
    collapse-level: 1
    content: auto
    pinned: false
    style: docked
    background: light
  page-footer: 
    left: "Copyright 2025, Iraitz Montalbán" 
    right: 
      - icon: github
        href: https://github.com/IraitzM
      - icon: linkedin 
        href: https://www.linkedin.com/in/iraitzmontalban/
    border: false
    background: light
  chapters:
    - index.qmd
    - content/intro.qmd

    - part: content/modelado/intro.qmd
      chapters:
      - content/modelado/formasnormales.qmd
      - content/modelado/desnormalizar.qmd

    - part: "Sistemas gestores de datos"
      chapters:
      - content/sistemas/intro.qmd

    - part: "Ingesta de datos"
      chapters:
      - content/load/intro.qmd

    - part: "Transformación de datos"
      chapters:
      - content/transform/intro.qmd

    - part: content/explotacion/intro.qmd
      chapters:
      - content/explotacion/bi.qmd
      - content/explotacion/ds.qmd

    - content/references.qmd

  appendices:
    - content/appendices/de_storybook.qmd

bibliography: content/references.bib

format:
  html:
    include-in-header: static/code_head.html
    include-before-body: static/code_body.html
    number-depth: 3
    theme: 
     - cosmo
     - style.scss
    code-link: true

# Some SEO
metadata:
  lang: es
  twitter-card: false
  open-graph: true
  image: cover.png

resources:
  - robots.txt

