[project]
name = "ingenieria-datos"
version = "0.1.0"
description = "Dependencias para la ejecución de código Python en la plataforma"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "nbclient>=0.10.2",
    "nbformat>=5.10.4",
    "pyyaml>=6.0.2",
]
