[project]
name = "ingenieria-datos"
version = "0.1.0"
description = "Dependencias para la ejecución de código Python en la plataforma"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-duckdb>=1.11.0",
    "dlt[duckdb,parquet,sqlalchemy]>=1.29.1",
    "duckdb>=1.5.5",
    "ibis-framework[duckdb]>=12.0.0",
    "ipykernel>=6.30.1",
    "model2vec>=0.8.2",
    "nbclient>=0.10.2",
    "nbformat>=5.10.4",
    "pandas>=3.0.5",
    "pyyaml>=6.0.2",
]
