<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Apéndice E — Ejercicio: un lago de datos entero – Ingeniería de datos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../content/appendices/de_storybook.html" rel="next">
<link href="../../content/appendices/rill.html" rel="prev">
<link href="../../cover.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5654c63b48dddc82f74614a25711f121.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-MXHDHE1HP5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-MXHDHE1HP5');
</script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PLKHBRCG');</script>
<!-- End Google Tag Manager -->

<meta name="keywords" content="Ingeniería de datos, dbt, dlt, data lake, data warehouse">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<meta property="og:title" content="Apéndice E — Ejercicio: un lago de datos entero – Ingeniería de datos">
<meta property="og:description" content="">
<meta property="og:image" content="https://iraitzm.github.io/ingenieria-datos/cover.png">
<meta property="og:site_name" content="Ingeniería de datos">
<meta property="og:image:height" content="1536">
<meta property="og:image:width" content="1024">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../content/appendices/variantes_modelado.html">Appendices</a></li><li class="breadcrumb-item"><a href="../../content/appendices/datalake.html"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Ejercicio: un lago de datos entero</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Ingeniería de datos</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/IraitzM/ingenieria-datos" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=|url|" title="LinkedIn" class="quarto-navigation-tool px-1" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prólogo</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../content/modelado/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modelado de datos</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/modelado/formasnormales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Formas normales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/modelado/desnormalizar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Desnormalizar</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/modelado/modelado_analitico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modelado analítico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/modelado/nuevos_paradigmas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Nuevos paradigmas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Sistemas gestores de datos</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/sistemas/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sistemas de gestión de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/sistemas/rdbms_transaccional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Base de datos operacional</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/sistemas/sql.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Structured Query Language</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/sistemas/dbms_analítica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Base de datos analítica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/sistemas/arquitecturas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Elección de arquitecturas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/sistemas/nuevos-formatos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Formatos abiertos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Ingesta de datos</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/load/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Extracción</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/load/patrones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Patrones de carga</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/load/herramientas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Herramientas de ingesta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/load/staging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">La capa de aterrizaje</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Transformación de datos</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/transform/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Transformación</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/transform/data_warehousing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">dbt sobre el lakehouse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/transform/raw_vault.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">El raw vault</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/transform/business_vault.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Business vault y consumo</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../content/explotacion/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explotación de los datos</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/explotacion/semantica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">La capa semántica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/explotacion/bi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inteligencia de negocio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/explotacion/ds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Ciencia de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/explotacion/ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Agentes y asistentes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/explotacion/mlops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Del cuaderno a producción</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/appendices/variantes_modelado.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Variantes de modelado</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/appendices/metadatado.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Metadatado y catálogo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/appendices/calidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Calidad de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/appendices/rill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Exploración con Rill</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/appendices/datalake.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Ejercicio: un lago de datos entero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/appendices/de_storybook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">La danza del Ingeniero de Datos</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#lo-que-se-va-a-levantar" id="toc-lo-que-se-va-a-levantar" class="nav-link active" data-scroll-target="#lo-que-se-va-a-levantar"><span class="header-section-number">E.1</span> Lo que se va a levantar</a></li>
  <li><a href="#antes-de-empezar" id="toc-antes-de-empezar" class="nav-link" data-scroll-target="#antes-de-empezar"><span class="header-section-number">E.2</span> Antes de empezar</a></li>
  <li><a href="#puesta-en-marcha" id="toc-puesta-en-marcha" class="nav-link" data-scroll-target="#puesta-en-marcha"><span class="header-section-number">E.3</span> Puesta en marcha</a>
  <ul class="collapse">
  <li><a href="#levantar-el-origen" id="toc-levantar-el-origen" class="nav-link" data-scroll-target="#levantar-el-origen"><span class="header-section-number">E.3.1</span> Levantar el origen</a></li>
  <li><a href="#cargar-la-capa-bronce" id="toc-cargar-la-capa-bronce" class="nav-link" data-scroll-target="#cargar-la-capa-bronce"><span class="header-section-number">E.3.2</span> Cargar la capa bronce</a></li>
  <li><a href="#construir-el-vault" id="toc-construir-el-vault" class="nav-link" data-scroll-target="#construir-el-vault"><span class="header-section-number">E.3.3</span> Construir el vault</a></li>
  <li><a href="#las-dos-cosas-de-una-vez" id="toc-las-dos-cosas-de-una-vez" class="nav-link" data-scroll-target="#las-dos-cosas-de-una-vez"><span class="header-section-number">E.3.4</span> Las dos cosas de una vez</a></li>
  <li><a href="#ver-el-linaje" id="toc-ver-el-linaje" class="nav-link" data-scroll-target="#ver-el-linaje"><span class="header-section-number">E.3.5</span> Ver el linaje</a></li>
  <li><a href="#escribir-la-documentación-una-sola-vez" id="toc-escribir-la-documentación-una-sola-vez" class="nav-link" data-scroll-target="#escribir-la-documentación-una-sola-vez"><span class="header-section-number">E.3.6</span> Escribir la documentación una sola vez</a></li>
  <li><a href="#vigilar-la-calidad" id="toc-vigilar-la-calidad" class="nav-link" data-scroll-target="#vigilar-la-calidad"><span class="header-section-number">E.3.7</span> Vigilar la calidad</a></li>
  <li><a href="#explorar" id="toc-explorar" class="nav-link" data-scroll-target="#explorar"><span class="header-section-number">E.3.8</span> Explorar</a></li>
  <li><a href="#preguntar-en-castellano" id="toc-preguntar-en-castellano" class="nav-link" data-scroll-target="#preguntar-en-castellano"><span class="header-section-number">E.3.9</span> Preguntar en castellano</a></li>
  <li><a href="#comprobar-que-está-todo" id="toc-comprobar-que-está-todo" class="nav-link" data-scroll-target="#comprobar-que-está-todo"><span class="header-section-number">E.3.10</span> Comprobar que está todo</a></li>
  </ul></li>
  <li><a href="#lo-que-ha-quedado-construido" id="toc-lo-que-ha-quedado-construido" class="nav-link" data-scroll-target="#lo-que-ha-quedado-construido"><span class="header-section-number">E.4</span> Lo que ha quedado construido</a></li>
  <li><a href="#las-decisiones-que-importan" id="toc-las-decisiones-que-importan" class="nav-link" data-scroll-target="#las-decisiones-que-importan"><span class="header-section-number">E.5</span> Las decisiones que importan</a>
  <ul class="collapse">
  <li><a href="#el-hub-se-carga-desde-todos-los-orígenes" id="toc-el-hub-se-carga-desde-todos-los-orígenes" class="nav-link" data-scroll-target="#el-hub-se-carga-desde-todos-los-orígenes"><span class="header-section-number">E.5.1</span> El hub se carga desde todos los orígenes</a></li>
  <li><a href="#los-satélites-no-se-cierran-se-deducen" id="toc-los-satélites-no-se-cierran-se-deducen" class="nav-link" data-scroll-target="#los-satélites-no-se-cierran-se-deducen"><span class="header-section-number">E.5.2</span> Los satélites no se cierran, se deducen</a></li>
  <li><a href="#el-enlace-no-lleva-atributos" id="toc-el-enlace-no-lleva-atributos" class="nav-link" data-scroll-target="#el-enlace-no-lleva-atributos"><span class="header-section-number">E.5.3</span> El enlace no lleva atributos</a></li>
  <li><a href="#lo-que-parece-un-atributo-y-es-una-entidad" id="toc-lo-que-parece-un-atributo-y-es-una-entidad" class="nav-link" data-scroll-target="#lo-que-parece-un-atributo-y-es-una-entidad"><span class="header-section-number">E.5.4</span> Lo que parece un atributo y es una entidad</a></li>
  <li><a href="#los-enlaces-también-tienen-versión-vigente" id="toc-los-enlaces-también-tienen-versión-vigente" class="nav-link" data-scroll-target="#los-enlaces-también-tienen-versión-vigente"><span class="header-section-number">E.5.5</span> Los enlaces también tienen versión vigente</a></li>
  <li><a href="#dos-identidades-para-la-misma-persona" id="toc-dos-identidades-para-la-misma-persona" class="nav-link" data-scroll-target="#dos-identidades-para-la-misma-persona"><span class="header-section-number">E.5.6</span> Dos identidades para la misma persona</a></li>
  <li><a href="#el-grano-manda" id="toc-el-grano-manda" class="nav-link" data-scroll-target="#el-grano-manda"><span class="header-section-number">E.5.7</span> El grano manda</a></li>
  <li><a href="#el-modelo-físico-de-un-erp-no-es-el-que-enseña" id="toc-el-modelo-físico-de-un-erp-no-es-el-que-enseña" class="nav-link" data-scroll-target="#el-modelo-físico-de-un-erp-no-es-el-que-enseña"><span class="header-section-number">E.5.8</span> El modelo físico de un ERP no es el que enseña</a></li>
  </ul></li>
  <li><a href="#ejercicios" id="toc-ejercicios" class="nav-link" data-scroll-target="#ejercicios"><span class="header-section-number">E.6</span> Ejercicios</a>
  <ul class="collapse">
  <li><a href="#ver-el-historial-en-funcionamiento" id="toc-ver-el-historial-en-funcionamiento" class="nav-link" data-scroll-target="#ver-el-historial-en-funcionamiento"><span class="header-section-number">E.6.1</span> Ver el historial en funcionamiento</a></li>
  <li><a href="#romper-la-integridad-a-propósito" id="toc-romper-la-integridad-a-propósito" class="nav-link" data-scroll-target="#romper-la-integridad-a-propósito"><span class="header-section-number">E.6.2</span> Romper la integridad a propósito</a></li>
  <li><a href="#trasladar-a-alguien-de-departamento" id="toc-trasladar-a-alguien-de-departamento" class="nav-link" data-scroll-target="#trasladar-a-alguien-de-departamento"><span class="header-section-number">E.6.3</span> Trasladar a alguien de departamento</a></li>
  <li><a href="#modelar-la-jerarquía-como-enlace" id="toc-modelar-la-jerarquía-como-enlace" class="nav-link" data-scroll-target="#modelar-la-jerarquía-como-enlace"><span class="header-section-number">E.6.4</span> Modelar la jerarquía como enlace</a></li>
  <li><a href="#añadir-un-origen" id="toc-añadir-un-origen" class="nav-link" data-scroll-target="#añadir-un-origen"><span class="header-section-number">E.6.5</span> Añadir un origen</a></li>
  <li><a href="#comprobar-al-agente" id="toc-comprobar-al-agente" class="nav-link" data-scroll-target="#comprobar-al-agente"><span class="header-section-number">E.6.6</span> Comprobar al agente</a></li>
  <li><a href="#calcular-el-margen" id="toc-calcular-el-margen" class="nav-link" data-scroll-target="#calcular-el-margen"><span class="header-section-number">E.6.7</span> Calcular el margen</a></li>
  </ul></li>
  <li><a href="#lo-que-hay-que-vigilar" id="toc-lo-que-hay-que-vigilar" class="nav-link" data-scroll-target="#lo-que-hay-que-vigilar"><span class="header-section-number">E.7</span> Lo que hay que vigilar</a></li>
  <li><a href="#lo-que-este-ejercicio-deja-fuera" id="toc-lo-que-este-ejercicio-deja-fuera" class="nav-link" data-scroll-target="#lo-que-este-ejercicio-deja-fuera"><span class="header-section-number">E.8</span> Lo que este ejercicio deja fuera</a></li>
  <li><a href="#desmontarlo" id="toc-desmontarlo" class="nav-link" data-scroll-target="#desmontarlo"><span class="header-section-number">E.9</span> Desmontarlo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PLKHBRCG" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../content/appendices/variantes_modelado.html">Appendices</a></li><li class="breadcrumb-item"><a href="../../content/appendices/datalake.html"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Ejercicio: un lago de datos entero</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Apéndice E — Ejercicio: un lago de datos entero</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>El resto del libro construye sobre la secretaría académica, un origen inventado a medida para que cada capítulo pueda enseñar una cosa sin que estorben las demás. Este apéndice propone el ejercicio contrario: <strong>partir de un sistema real y llegar hasta el panel</strong>, con todo lo que eso trae. El origen es <a href="https://www.odoo.com/">Odoo</a>, un ERP de código abierto con datos de demostración, y la gracia está precisamente en que su base de datos no está diseñada para que la analicemos.</p>
<p>Todo lo necesario está en el repositorio. Basta con este apéndice y los ficheros que se citan para reconstruirlo desde cero, y conviene hacerlo en ese orden, porque cada paso deja algo que el siguiente necesita.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Es un ejercicio aparte
</div>
</div>
<div class="callout-body-container callout-body">
<p>Este montaje no continúa el ejemplo de la academia ni comparte nada con él. Los puertos están elegidos para que ambos puedan convivir en la misma máquina, así que se puede tener el libro renderizando y este lago levantado a la vez.</p>
</div>
</div>
<section id="lo-que-se-va-a-levantar" class="level2" data-number="E.1">
<h2 data-number="E.1" class="anchored" data-anchor-id="lo-que-se-va-a-levantar"><span class="header-section-number">E.1</span> Lo que se va a levantar</h2>
<p>Ocho piezas, todas de código abierto, cada una haciendo exactamente un trabajo.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    o[("Odoo&lt;br/&gt;PostgreSQL")] --&gt; d["dlt"]
    d --&gt; b[("DuckDB&lt;br/&gt;raw")]
    b --&gt; t["dbt"]
    t --&gt; v[("DuckDB&lt;br/&gt;vault")]
    v --&gt; t2["dbt"]
    t2 --&gt; g[("DuckDB&lt;br/&gt;oro")]
    g --&gt; r["Rill"]
    g --&gt; n["nao"]
    g --&gt; s["Soda"]
    t2 -.-&gt; doc["dbt docs"]
    t2 -.-&gt; n
    s -.-&gt; m[("DuckDB&lt;br/&gt;meta")]
    t2 -.-&gt; m
    m -.-&gt; r
    m -.-&gt; n

    classDef origen fill:#ececf0,stroke:#868d9c,stroke-width:1.5px,color:#2b2f3a
    classDef carga fill:#fae3c8,stroke:#bf7f28,stroke-width:1.5px,color:#573809
    classDef almacen fill:#d5e6f5,stroke:#3d7cb0,stroke-width:1.5px,color:#12354e
    classDef transformacion fill:#d7eddc,stroke:#4a9463,stroke-width:1.5px,color:#1c4a2e
    classDef explotacion fill:#e6ddf5,stroke:#7457bd,stroke-width:1.5px,color:#332757
    classDef documentacion fill:#d7eddc,stroke:#4a9463,stroke-width:1.5px,color:#1c4a2e,stroke-dasharray:4 3
    classDef meta fill:#d9efec,stroke:#3a8f8a,stroke-width:1.5px,color:#0f3f3c
    class o origen
    class d carga
    class b,v,g almacen
    class t,t2 transformacion
    class r,n explotacion
    class doc,s documentacion
    class m meta
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Las flechas de puntos no llevan datos, llevan <strong>lo que sabemos sobre los datos</strong>. dbt docs no transforma nada, se limita a publicar lo que dbt sabe de sus propios modelos. La que llega a nao es de la misma naturaleza y es la que hace interesante a esa pieza: el agente recibe el dato por un lado y <strong>el proyecto de dbt por el otro</strong>, porque para contestar bien no le basta con ver las tablas, necesita saber qué decidimos al construirlas.</p>
<p>Y las que confluyen en <code>meta</code> son las que casi nunca se dibujan. Ahí acaban el resultado de las pruebas de dbt, la frescura de las fuentes y los avisos de Soda, que de otro modo se quedarían en tres ficheros JSON que nadie vuelve a abrir. Desde ahí las leen el panel y el agente, que es lo que permite preguntar si un número es de fiar en el mismo sitio donde se mira el número.</p>
<table class="caption-top table">
<caption>Las piezas del ejercicio y dónde encontrarlas</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Pieza</th>
<th>Papel</th>
<th>Dónde queda</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Odoo 16 y PostgreSQL 15</td>
<td>Sistema origen, con los módulos de ventas y recursos humanos y sus datos de demostración</td>
<td><code>http://localhost:8069</code></td>
</tr>
<tr class="even">
<td>dlt</td>
<td>Ingesta de Odoo al almacén</td>
<td><code>pipelines/odoo_extract.py</code></td>
</tr>
<tr class="odd">
<td>DuckDB</td>
<td>El almacén, las cuatro capas</td>
<td><code>warehouse/warehouse.duckdb</code></td>
</tr>
<tr class="even">
<td>dbt</td>
<td>Data Vault y capa de explotación</td>
<td><code>dbt_project/</code></td>
</tr>
<tr class="odd">
<td>dbt docs</td>
<td>Diccionario de modelos y grafo de linaje</td>
<td><code>http://localhost:8081</code></td>
</tr>
<tr class="even">
<td>Soda</td>
<td>Vigilancia de calidad sobre la capa oro</td>
<td><code>soda_project/</code></td>
</tr>
<tr class="odd">
<td>Rill</td>
<td>Paneles de exploración</td>
<td><code>http://localhost:9010</code></td>
</tr>
<tr class="even">
<td>nao</td>
<td>Agente analítico sobre la capa oro</td>
<td><code>http://localhost:5005</code></td>
</tr>
</tbody>
</table>
<p>Soda es la única sin dirección web: no tiene interfaz propia en este montaje a propósito, porque su resultado no acaba en un informe suyo sino en el almacén, junto al dato que vigila.</p>
<p>Los puertos no son los de costumbre y la razón es evitar choques: el 3000 lo usa Evidence en el <a href="../../content/explotacion/bi.html">capítulo de inteligencia de negocio</a>, el 8585 lo ocupa OpenMetadata en el <a href="../../content/appendices/metadatado.html">apéndice de metadatado</a> y el 9009 es el de un Rill arrancado en local como se ve en el <a href="../../content/appendices/rill.html">apéndice de exploración</a>. Aquí PostgreSQL se publica en el 5433, Rill en el 9010 y la documentación en el 8081 (dbt docs sirve por defecto en el 8080, que es de los puertos más disputados de cualquier portátil). nao se queda en su 5005 de siempre, que no lo disputa nadie.</p>
</section>
<section id="antes-de-empezar" class="level2" data-number="E.2">
<h2 data-number="E.2" class="anchored" data-anchor-id="antes-de-empezar"><span class="header-section-number">E.2</span> Antes de empezar</h2>
<p>Hace falta Docker con el complemento <code>compose</code> y unos 4 GiB de memoria libre. De disco, unos 3 GiB para llegar hasta el panel y <strong>unos 7 GiB si se monta también el agente</strong>: la imagen de nao ocupa 3,5 GiB ella sola, más que todo lo demás junto. Es una cifra que conviene saber antes y no a mitad de descarga, y una razón perfectamente legítima para dejar esa última pieza para otro día: el ejercicio está completo sin ella.</p>
<p>La primera ejecución tarda lo que tarde la descarga.</p>
</section>
<section id="puesta-en-marcha" class="level2" data-number="E.3">
<h2 data-number="E.3" class="anchored" data-anchor-id="puesta-en-marcha"><span class="header-section-number">E.3</span> Puesta en marcha</h2>
<section id="levantar-el-origen" class="level3" data-number="E.3.1">
<h3 data-number="E.3.1" class="anchored" data-anchor-id="levantar-el-origen"><span class="header-section-number">E.3.1</span> Levantar el origen</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose up <span class="at">-d</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Esto arranca PostgreSQL, crea la base de datos de Odoo con los módulos de ventas y recursos humanos y sus datos de demostración, y deja el ERP escuchando. La creación de la base de datos la hace un servicio de un solo uso (<code>odoo-init</code>) en lugar del asistente web, que es lo que suele proponerse y que tiene el inconveniente de no ser reproducible: obliga a rellenar un formulario a mano y a acordarse de marcar la casilla de los datos de demostración.</p>
<p>Los módulos se instalan de una vez en la orden del servicio, y no son gratis en el sentido que importa aquí:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">command</span><span class="kw">:</span><span class="at"> </span><span class="kw">[</span><span class="st">"odoo"</span><span class="kw">,</span><span class="at"> </span><span class="st">"-d"</span><span class="kw">,</span><span class="at"> </span><span class="st">"odoo_demo"</span><span class="kw">,</span><span class="at"> </span><span class="st">"-i"</span><span class="kw">,</span><span class="at"> </span><span class="st">"sale_management,hr"</span><span class="kw">,</span><span class="at"> </span><span class="st">"--stop-after-init"</span><span class="kw">]</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El primer arranque tarda un par de minutos en inicializar la base. Se sabe que ha terminado cuando el servicio de inicialización ha salido con código cero:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> inspect dl-odoo-init <span class="at">--format</span> <span class="st">'{{.State.ExitCode}}'</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>A partir de ahí Odoo responde en <code>http://localhost:8069</code>, con usuario <code>admin</code> y contraseña <code>admin</code>. Merece la pena entrar y mirar los pedidos de venta, aunque solo sea para tener presente cómo se ven los datos antes de que los toquemos.</p>
</section>
<section id="cargar-la-capa-bronce" class="level3" data-number="E.3.2">
<h3 data-number="E.3.2" class="anchored" data-anchor-id="cargar-la-capa-bronce"><span class="header-section-number">E.3.2</span> Cargar la capa bronce</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> extract</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>dlt lee diez tablas de Odoo y las deja en el esquema <code>raw</code> sin más cambio que el nombre. Al terminar informa de lo cargado, y estos son los números que salen con los datos de demostración:</p>
<pre><code>raw.raw_customers: 66
raw.raw_orders: 20
raw.raw_order_lines: 44
raw.raw_products: 34
raw.raw_product_templates: 29
raw.raw_product_categories: 9
raw.raw_employees: 20
raw.raw_departments: 7
raw.raw_sales_teams: 5
raw.raw_countries: 250</code></pre>
<p>Si esos números no cuadran, no tiene sentido seguir: algo ha fallado en el origen y todo lo que venga después heredará el problema.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Once columnas de cincuenta y ocho
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>hr_employee</code> es la tabla que obliga a pensar antes de copiar. Tiene cincuenta y ocho columnas y en <code>ODOO_TABLES</code> solo se declaran once, porque entre las otras cuarenta y siete están el número de la seguridad social, el pasaporte, la fecha de nacimiento, el estado civil, el género y el permiso de trabajo.</p>
<p>Son datos personales de categoría especial y <strong>el almacén analítico no tiene ninguna razón para verlos</strong>. Que la ingesta declare las columnas una a una en lugar de hacer un <code>SELECT *</code> deja de ser una manía de estilo y pasa a ser el control que lo impide: con la lista explícita, incorporar un dato sensible exige escribirlo, y eso aparece en la revisión del cambio. Con <code>SELECT *</code>, entra solo el día que alguien añada un campo en el ERP y nadie se entera.</p>
</div>
</div>
</section>
<section id="construir-el-vault" class="level3" data-number="E.3.3">
<h3 data-number="E.3.3" class="anchored" data-anchor-id="construir-el-vault"><span class="header-section-number">E.3.3</span> Construir el vault</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> transform</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>dbt encadena las tres capas que quedan (staging, vault y explotación) y a continuación ejecuta las pruebas. La salida termina así:</p>
<pre><code>Done. PASS=216 WARN=0 ERROR=0 SKIP=0 TOTAL=216</code></pre>
<p>Los doscientos dieciséis incluyen treinta y siete modelos y ciento setenta y nueve pruebas. Que pasen todas no significa que el modelo sea bueno, pero que falle una sí significa que algo está mal, y en este proyecto hay pruebas puestas justo donde el Data Vault se rompe con más facilidad.</p>
</section>
<section id="las-dos-cosas-de-una-vez" class="level3" data-number="E.3.4">
<h3 data-number="E.3.4" class="anchored" data-anchor-id="las-dos-cosas-de-una-vez"><span class="header-section-number">E.3.4</span> Las dos cosas de una vez</h3>
<p>Los dos pasos anteriores pueden ejecutarse como un solo proceso, porque dlt sabe lanzar un proyecto dbt por su cuenta:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> pipeline</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Está en <code>pipelines/run_pipeline.py</code> y son tres líneas de fondo: se crea el pipeline, se carga y se le pasa el mismo objeto a <code>dlt.dbt.package()</code>, que deduce de él a qué base de datos tiene que apuntar dbt. La dependencia entre cargar y transformar no hay que declararla en ningún sitio, porque si la carga lanza una excepción la línea siguiente no llega a ejecutarse.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span><code>run_all</code> no ejecuta las pruebas
</div>
</div>
<div class="callout-body-container callout-body">
<p>El nombre engaña. <code>run_all()</code> hace <code>dbt deps</code>, <code>dbt seed</code> y <code>dbt run</code>, es decir el equivalente a <code>dbt run</code> y no a <code>dbt build</code>: <strong>las pruebas de los modelos no entran</strong>. Quedarse ahí dejaría el vault sin sus ciento setenta y nueve comprobaciones y sin enterarse. Por eso el script pide las pruebas aparte, con <code>transformacion.test()</code>, y suma los dos resultados antes de decidir si ha ido bien.</p>
</div>
</div>
</section>
<section id="ver-el-linaje" class="level3" data-number="E.3.5">
<h3 data-number="E.3.5" class="anchored" data-anchor-id="ver-el-linaje"><span class="header-section-number">E.3.5</span> Ver el linaje</h3>
<p>Cada <code>ref()</code> y cada <code>source()</code> del proyecto es una dependencia declarada, así que dbt conoce el grafo entero sin que nadie se lo cuente. Publicarlo como sitio web son dos pasos:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> transform dbt docs generate</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose <span class="at">--profile</span> docs up <span class="at">-d</span> docs</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El primero deja en <code>dbt_project/target/</code> el <code>manifest.json</code> (los modelos y sus dependencias) y el <code>catalog.json</code> (las columnas y los tipos de cada relación, que sí hay que ir a preguntarle a DuckDB). El segundo sirve esos ficheros en <code>http://localhost:8081</code>. El botón azul de la esquina inferior derecha abre el grafo:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../assets/dbt-linaje.png" class="img-fluid figure-img"></p>
<figcaption>Linaje de datos en dbt docs</figcaption>
</figure>
</div>
<p>Se lee de izquierda a derecha y es exactamente el recorrido que cuenta este apéndice: en verde las diez tablas de <code>raw</code> que dejó dlt, y en azul las diez vistas de staging, los seis hubs, los cinco enlaces, los siete satélites, las dos tablas de referencia y los siete modelos de explotación. Los nodos <code>satelite_grano_unico</code> y <code>cobertura_comercial</code> no son modelos sino las pruebas singulares de <code>dbt_project/tests/</code>, porque en el grafo de dbt <strong>las pruebas son nodos como cualquier otro</strong>: cuelgan de aquello que comprueban, que es justo lo que permite a <code>dbt build</code> ordenar la ejecución sin que nadie escriba las dependencias a mano.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Servir no bloquea el almacén, generar sí
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>dbt docs serve</code> es un servidor de ficheros estáticos: reparte el <code>manifest.json</code> y el <code>catalog.json</code> que ya están en <code>target/</code> y <strong>no abre DuckDB en ningún momento</strong>. Por eso este servicio sí convive con Rill, al contrario que <code>extract</code>, <code>transform</code> o <code>pipeline</code>.</p>
<p>Quien sí abre el almacén es <code>dbt docs generate</code>, porque el catálogo de columnas tiene que consultarlo. Con Rill levantado falla con el mismo <code>Conflicting lock is held in PID 0</code> de siempre, de modo que el orden que funciona es generar la documentación primero y arrancar el panel después.</p>
</div>
</div>
</section>
<section id="escribir-la-documentación-una-sola-vez" class="level3" data-number="E.3.6">
<h3 data-number="E.3.6" class="anchored" data-anchor-id="escribir-la-documentación-una-sola-vez"><span class="header-section-number">E.3.6</span> Escribir la documentación una sola vez</h3>
<p>Las descripciones que aparecen al pinchar un modelo salen de los <code>description:</code> de los cuatro ficheros YAML del proyecto. No hay nada automático en esa parte: lo que no esté escrito ahí sale vacío, y un diccionario de datos sin descripciones es poco más que la lista de columnas que ya da la base de datos.</p>
<p>Con treinta y siete modelos esa escritura tiene un problema que con cuatro no se notaba. Las columnas <code>load_date</code>, <code>record_source</code> y <code>hashdiff</code> aparecen en los veinte modelos del vault, y describirlas en cada YAML son veinte copias del mismo párrafo esperando a desincronizarse en cuanto alguien corrija una. La respuesta de dbt son los <strong>bloques de documentación</strong>: texto con nombre, guardado aparte, que se referencia desde donde haga falta.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>{% docs dv_load_date %}</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Momento en el que esta fila entró en el almacén. **No es una fecha de</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>negocio**: no dice cuándo ocurrió el hecho, dice cuándo nos enteramos.</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>{% enddocs %}</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Y en el YAML del modelo:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">-</span><span class="at"> </span><span class="fu">name</span><span class="kw">:</span><span class="at"> load_date</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">description</span><span class="kw">:</span><span class="at"> </span><span class="st">"{{ doc('dv_load_date') }}"</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Los bloques viven en <code>dbt_project/docs/</code>, declarado en <code>dbt_project.yml</code> con <code>docs-paths</code>. Son quince y se reparten en dos ficheros con propósitos distintos, que es la separación que conviene copiar:</p>
<ul>
<li><code>columnas_vault.md</code> describe las <strong>columnas técnicas</strong> del patrón (las claves hash, la fecha de carga, la huella de cambios). Contesta a “¿qué es esta columna?”.</li>
<li><code>entidades.md</code> describe las <strong>entidades de negocio</strong> (qué es un cliente aquí, qué es un empleado, por qué el equipo comercial no tiene hub). Contesta a “¿qué es esta cosa?”, que es la pregunta que más discusiones ahorra y la que ningún esquema de base de datos responde. Es el germen de un glosario, y por eso se referencia tanto desde el hub como desde el modelo de la capa oro: la misma definición sale en los dos sitios.</li>
</ul>
<p>Hay un bloque con nombre reservado, <code>__overview__</code>, que sustituye la portada del sitio por la que se quiera. La que trae el proyecto explica las cuatro capas y por dónde empezar a mirar, que es más útil que la página genérica de dbt para quien abre esto por primera vez.</p>
<p>El límite del grafo se ve mejor con la imagen delante: dbt solo dibuja lo que pasa por sus <code>ref()</code> y sus <code>source()</code>. El tramo de Odoo a <code>raw</code> lo hizo dlt y aquí no existe (las tablas de <code>raw</code> aparecen como el principio del mundo, cuando son la mitad de la historia), y el panel de Rill que consume la capa oro tampoco. Coser los tres tramos es precisamente el trabajo de un catálogo de gobierno, y cómo se reconstruye ese linaje completo a partir del <code>manifest.json</code> de dbt y del esquema que deja dlt está en el <a href="../../content/appendices/metadatado.html#trazabilidad-de-principio-a-fin-con-dlt-y-dbt">apéndice de metadatado</a>.</p>
</section>
<section id="vigilar-la-calidad" class="level3" data-number="E.3.7">
<h3 data-number="E.3.7" class="anchored" data-anchor-id="vigilar-la-calidad"><span class="header-section-number">E.3.7</span> Vigilar la calidad</h3>
<p>Llegados aquí hay ciento setenta y nueve pruebas de dbt en verde, y conviene fijarse en dos cosas que <strong>no</strong> se saben todavía.</p>
<p>La primera es si el dato sigue llegando. Las fuentes tienen declarada su frescura desde el principio, en <code>_stg_sources.yml</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sources</span><span class="kw">:</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> </span><span class="fu">name</span><span class="kw">:</span><span class="at"> raw</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">loaded_at_field</span><span class="kw">:</span><span class="at"> _extracted_at</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">freshness</span><span class="kw">:</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="fu">warn_after</span><span class="kw">:</span><span class="at"> </span><span class="kw">{</span><span class="fu">count</span><span class="kw">:</span><span class="at"> </span><span class="dv">12</span><span class="kw">,</span><span class="at"> </span><span class="fu">period</span><span class="kw">:</span><span class="at"> hour</span><span class="kw">}</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="fu">error_after</span><span class="kw">:</span><span class="at"> </span><span class="kw">{</span><span class="fu">count</span><span class="kw">:</span><span class="at"> </span><span class="dv">24</span><span class="kw">,</span><span class="at"> </span><span class="fu">period</span><span class="kw">:</span><span class="at"> hour</span><span class="kw">}</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Y esa declaración no la ejecutaba nadie. <code>dbt build</code> no incluye la frescura: hay que pedirla aparte.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> transform dbt source freshness</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>La segunda es todo lo que las pruebas de dbt no preguntan por diseño. Una prueba de dbt comprueba que <strong>el modelo cumple lo que dijimos al escribirlo</strong>: que la clave es única, que el enlace no cuelga. La calidad de datos es otra cosa, es vigilar que el mundo real sigue pareciéndose a lo que asumimos, sabiendo que no lo hará. Esa mitad la cubre <a href="https://www.soda.io/">Soda</a>, con el reparto que explica el <a href="../../content/appendices/calidad.html">apéndice de calidad</a>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> soda</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Con los datos de demostración el escaneo termina así:</p>
<pre><code>1/16 checks WARNED:
    customer_360 in almacen
      País informado en la ficha de cliente [WARNED]
        check_value: 34.85</code></pre>
<p>Merece la pena parar en ese número. <strong>El 34,85 % de las fichas de cliente no tiene país</strong>, y ninguna de las ciento setenta y nueve pruebas de dbt lo había mencionado, porque no hay nada incorrecto: Odoo no obliga a informar ese campo y el modelo nunca prometió que estuviera. Es exactamente el tipo de cosa que se descubre cuando alguien filtra un panel por país y le faltan un tercio de los clientes.</p>
<p>Por eso avisa en lugar de fallar:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">-</span><span class="at"> </span><span class="fu">missing_percent(country_name)</span><span class="kw">:</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">warn</span><span class="kw">:</span><span class="at"> when &gt; 20 %</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">fail</span><span class="kw">:</span><span class="at"> when &gt; 60 %</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">name</span><span class="kw">:</span><span class="at"> </span><span class="st">"País informado en la ficha de cliente"</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Un umbral que corta la carga por esto convierte un dato conocido del origen en una incidencia de plataforma, y lo que consigue a la larga es que alguien suba el umbral hasta que deje de molestar.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lo que el núcleo de Soda no puede hacer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dos de los controles más útiles de SodaCL no están en <code>checks/oro.yml</code>, y no es un olvido:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">-</span><span class="at"> change avg 7d for row_count &lt; 25 %</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="kw">-</span><span class="at"> </span><span class="fu">schema</span><span class="kw">:</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">warn</span><span class="kw">:</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="fu">when schema changes</span><span class="kw">:</span><span class="at"> any</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Los dos necesitan <strong>historia</strong>, y el núcleo de código abierto no la guarda: cada escaneo empieza de cero y no sabe qué dio el de ayer. Esa memoria la pone Soda Cloud, que no es abierto. Aquí la historia nos la guardamos nosotros en <code>meta.perfil_historico</code>, que es más trabajo y tiene la ventaja de que la serie queda en el almacén, consultable con SQL junto a todo lo demás.</p>
</div>
</div>
<section id="dónde-acaba-todo-esto-y-por-qué-no-en-dbt-docs" class="level4">
<h4 class="anchored" data-anchor-id="dónde-acaba-todo-esto-y-por-qué-no-en-dbt-docs">Dónde acaba todo esto (y por qué no en dbt docs)</h4>
<p>Tenemos tres comprobaciones distintas y tres artefactos que no se hablan: <code>run_results.json</code> con las pruebas, <code>sources.json</code> con la frescura y el JSON de Soda con los avisos. Ninguno se consulta con SQL, y aquí está lo que sorprende a casi todo el mundo:</p>
<p><strong>El sitio de documentación de dbt no enseña ninguno de los tres.</strong> Su <code>index.html</code> solo carga <code>manifest.json</code> y <code>catalog.json</code>. Se puede comprobar:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span> <span class="at">-o</span> <span class="st">"sources\.json\|catalog\.json\|manifest\.json\|run_results\.json"</span> <span class="dt">\</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="va">$(</span><span class="ex">python</span> <span class="at">-c</span> <span class="st">"import dbt,os;print(os.path.dirname(dbt.__file__))"</span><span class="va">)</span>/task/docs/index.html <span class="kw">|</span> <span class="fu">sort</span> <span class="at">-u</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>De modo que en dbt docs se ve que <strong>existe</strong> una prueba y que se <strong>declaró</strong> una frescura de doce horas, y nunca si están en verde. Es un catálogo de definiciones, no de estado, y confundir las dos cosas es fácil porque la interfaz no lo advierte en ninguna parte. La pregunta “¿me puedo fiar de esta tabla?” no se responde ahí.</p>
<p>Se responde donde están los datos, que es lo que defiende el <a href="../../content/appendices/calidad.html#aterrizarlo-en-la-base-de-metadatos">apéndice de calidad</a>. El último paso recoge los tres artefactos y los carga en un esquema <code>meta</code> del propio DuckDB:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> metadatos</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>meta.activos:    47
meta.controles:  195
meta.frescura:   10
meta.perfil:     7

Veredicto de la capa publicada:
  apto: 6
  con avisos: 1</code></pre>
<p>Los ciento noventa y cinco controles son las ciento setenta y nueve pruebas de dbt más los dieciséis de Soda, en una sola tabla con una columna que dice quién los ejecutó y otra que dice si cortan la carga. Y los cuarenta y siete activos incluyen las diez fuentes, que son las únicas que tienen frescura: si <code>raw_orders</code> deja de llegar, todo lo que hay debajo sigue en verde durante días porque el problema no está en las transformaciones.</p>
<p>A partir de ahí, fiarse de una tabla es una consulta:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> activo, capa, controles, avisos, fallos, veredicto, escaneado_en</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> meta.veredicto</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> capa <span class="op">=</span> <span class="st">'analytics'</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> fallos <span class="kw">DESC</span>, avisos <span class="kw">DESC</span>;</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Esa vista tiene una cuarta categoría además de <code>apto</code>, <code>con avisos</code> y <code>con fallos</code>, y es la más útil de las cuatro: <strong><code>sin vigilancia</code></strong>. Una tabla que no falla ningún control porque no tiene ninguno no es una tabla sana, es una tabla sobre la que no sabemos nada, y conviene que las dos cosas no se parezcan en el informe. En este proyecto no hay ninguna, y comprobarlo con una consulta vale más que suponerlo.</p>
<p>La columna <code>escaneado_en</code> está en todas las tablas de <code>meta</code> y tampoco es decorativa: sin ella no se distingue “esto está bien” de “esto estaba bien hace tres semanas y nadie ha vuelto a mirar”.</p>
</section>
<section id="el-recorrido-completo" class="level4">
<h4 class="anchored" data-anchor-id="el-recorrido-completo">El recorrido completo</h4>
<p>Con la calidad dentro, la secuencia entera del ejercicio son cuatro órdenes:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> pipeline                        <span class="co"># ingesta y transformación</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> transform dbt source freshness  <span class="co"># ¿sigue llegando el dato?</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> soda                            <span class="co"># ¿se parece a lo esperado?</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> metadatos                       <span class="co"># todo junto y consultable</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El atajo <code>pipeline</code> cubre solo las dos primeras capas: la vigilancia se pide aparte a propósito, porque son comprobaciones sobre lo ya publicado y no un paso más de la construcción.</p>
</section>
</section>
<section id="explorar" class="level3" data-number="E.3.8">
<h3 data-number="E.3.8" class="anchored" data-anchor-id="explorar"><span class="header-section-number">E.3.8</span> Explorar</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose <span class="at">--profile</span> bi up <span class="at">-d</span> rill</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El panel queda en <code>http://localhost:9010</code>. Rill consulta el mismo fichero DuckDB que acaba de construir dbt, sin copiar nada.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../assets/ri.png" class="img-fluid figure-img"></p>
<figcaption>El panel de ventas en Rill</figcaption>
</figure>
</div>
<p>Lo que hay dentro son cuatro pantallas y tres vistas de métricas, y el reparto no es decorativo:</p>
<table class="caption-top table">
<caption>Los recursos del proyecto de Rill</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Recurso</th>
<th>Tabla que ataca</th>
<th>Grano</th>
<th>Para qué</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>metrics/ventas.yaml</code></td>
<td><code>point_in_time_orders</code></td>
<td>Pedido</td>
<td>Facturación, ticket medio, reparto por comercial y departamento</td>
</tr>
<tr class="even">
<td><code>metrics/catalogo.yaml</code></td>
<td><code>point_in_time_order_lines</code></td>
<td>Línea de pedido</td>
<td>Unidades, precio medio ponderado, descuentos por producto y categoría</td>
</tr>
<tr class="odd">
<td><code>metrics/plantilla.yaml</code></td>
<td><code>employee_360</code></td>
<td>Empleado</td>
<td>Quién hay, dónde y qué parte de la plantilla vende</td>
</tr>
<tr class="even">
<td><code>metrics/calidad.yaml</code></td>
<td><code>calidad_controles</code></td>
<td>Control ejecutado</td>
<td>Si el almacén está vigilado y en verde</td>
</tr>
<tr class="odd">
<td><code>canvas/resumen.yaml</code></td>
<td>Las cuatro</td>
<td>Composición fija</td>
<td>La portada que se mira sin tocar nada</td>
</tr>
</tbody>
</table>
<p>La cuarta es la rara y merece un apunte: no mide el negocio sino el almacén, de modo que una cifra que sube ahí no es una buena noticia. Su tabla es una vista en <code>main</code> sobre <code>meta.controles</code>, y existe por la misma limitación que obligó a materializar la capa oro en <code>main</code>: Rill no sabe mirar fuera del esquema por defecto, así que los metadatos se quedan en <code>meta</code> y lo que se publica es el puente.</p>
<p>Las tres vistas de métricas consultan el mismo almacén y <strong>no se pueden mezclar</strong>, porque miden granos distintos. Se ve en la definición de la misma cifra: en <code>ventas</code> la facturación es <code>sum(amount_total)</code> sobre la cabecera del pedido, y en <code>catalogo</code> es <code>sum(price_total)</code> sobre la línea. Sumar la primera a grano de línea la multiplicaría por el número de líneas de cada pedido, y el total saldría inflado sin que nada avisara.</p>
<p>Que la capa semántica obligue a declarar de qué tabla sale cada medida es justamente lo que hace imposible ese error: nadie puede pedir la facturación del pedido desglosada por producto, porque esa combinación no existe en ninguna de las dos vistas. Es la diferencia entre una capa semántica y una carpeta de consultas guardadas.</p>
<p>El <code>canvas</code> es el tercer tipo de recurso y responde a una necesidad distinta de la del <code>explore</code>. Un <code>explore</code> es una herramienta de investigación: se entra sin saber qué se busca. Un <code>canvas</code> es una composición fija, para la pantalla que alguien mira cada lunes. Puede juntar bloques de las tres vistas de métricas en una misma página porque cada bloque declara de cuál bebe.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>El rango temporal por defecto decide la primera impresión
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sin declarar <code>defaults</code>, Rill abre el panel en las últimas veinticuatro horas. Con estos datos de demostración eso deja fuera casi todo el histórico: la portada aparece medio vacía y la serie temporal, plana. Dos líneas de configuración (<code>time_ranges</code> y <code>defaults: time_range</code>) son la diferencia entre un panel que se entiende al abrirlo y uno que parece roto.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Rill bloquea el almacén
</div>
</div>
<div class="callout-body-container callout-body">
<p>DuckDB admite un único escritor sobre el fichero, por las razones que se explican en el <a href="../../content/sistemas/dbms_analítica.html#embebido-o-servidor">capítulo de bases de datos analíticas</a>. Mientras Rill esté levantado, <strong>cualquiera de las órdenes que escriben</strong> (<code>extract</code>, <code>transform</code> o <code>pipeline</code>) falla con un <code>Conflicting lock is held in PID 0</code>. Ese <code>PID 0</code> despista, porque el proceso que tiene el bloqueo está en otro contenedor y desde aquí no se le ve el número.</p>
<p>La solución es parar el panel antes de volver a cargar:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose stop rill</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Por eso Rill vive tras un perfil de Compose y no arranca con el <code>up -d</code> general: el orden natural (cargar, transformar y después explorar) evita el choque. Al terminar de reconstruir, <code>docker compose --profile bi up -d rill</code> lo devuelve a su sitio.</p>
</div>
</div>
</section>
<section id="preguntar-en-castellano" class="level3" data-number="E.3.9">
<h3 data-number="E.3.9" class="anchored" data-anchor-id="preguntar-en-castellano"><span class="header-section-number">E.3.9</span> Preguntar en castellano</h3>
<p>La última pieza es <a href="https://getnao.io/">nao</a>, un agente analítico de código abierto. Complementario al agente nativo de Rill aunque con algún extra respecto al acceso a documentación adicional a la de la capa semántica.</p>
<p>Se monta en dos pasos y la separación entre ellos es la misma que ya vimos con dbt docs:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> nao-context</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose <span class="at">--profile</span> ai up <span class="at">-d</span> nao</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El primero construye el <strong>contexto</strong>: recorre la capa oro y el proyecto de dbt y deja en <code>nao_project/</code> una carpeta de ficheros markdown describiendo lo que hay. El segundo levanta el chat en <code>http://localhost:5005</code>, que consume ese contexto. Generar necesita el almacén; servir, no. Hay que rehacer el contexto cuando cambie el modelo, exactamente igual que <code>dbt docs generate</code>.</p>
<p>Al entrar la primera vez pide crear una cuenta, que es local del contenedor.</p>
<section id="lo-que-se-le-enseña-y-lo-que-no" class="level4">
<h4 class="anchored" data-anchor-id="lo-que-se-le-enseña-y-lo-que-no">Lo que se le enseña, y lo que no</h4>
<p>Aquí está la decisión de diseño de esta pieza, y es la que más se nota al usarla. En <code>nao_project/nao_config.yaml</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">databases</span><span class="kw">:</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> </span><span class="fu">name</span><span class="kw">:</span><span class="at"> almacen</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">type</span><span class="kw">:</span><span class="at"> duckdb</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">path</span><span class="kw">:</span><span class="at"> /data/warehouse.duckdb</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">include</span><span class="kw">:</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="kw">-</span><span class="at"> </span><span class="st">"main.*"</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Solo la capa oro.</strong> La tentación es apuntar el agente a todo el almacén, que total ya está ahí, y es un error que se paga en la primera respuesta: desde <code>raw</code> el nombre del producto es un JSON, los presupuestos se mezclan con los pedidos y el contador de clientes miente. Todo el trabajo de las capas intermedias existe precisamente para que nadie tenga que contestar desde ahí. Dejarlas al alcance del agente sería tirarlo por la ventana en el último paso.</p>
<p>El vault tampoco entra: guarda la historia, pero responder con él exige encadenar hubs y satélites, y eso ya lo hace la capa oro una vez. Con el filtro puesto, el agente ve siete tablas.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>El patrón se compara con <code>esquema.tabla</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>main</code> a secas no casa con <code>main.kpis_daily</code>, así que el asterisco no es decorativo. Sin él, el sync termina con un <code>Nothing to sync</code> en verde, sin errores y sin contexto, que es de las formas más incómodas de fallar: parece que ha ido bien.</p>
</div>
</div>
<p>La segunda mitad de la configuración es la que de verdad cambia las respuestas:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">repos</span><span class="kw">:</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> </span><span class="fu">name</span><span class="kw">:</span><span class="at"> dbt</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">local_path</span><span class="kw">:</span><span class="at"> /app/dbt_project</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">include</span><span class="kw">:</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="kw">-</span><span class="at"> </span><span class="st">"models/**/*.sql"</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="kw">-</span><span class="at"> </span><span class="st">"models/**/*.yml"</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="kw">-</span><span class="at"> </span><span class="st">"docs/**/*.md"</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El proyecto de dbt entero como contexto. Aquí está lo que la base de datos no puede contarle: el SQL de cada modelo, las pruebas y, sobre todo, las descripciones de los YAML y los bloques de <code>docs/</code>. <strong>Ese es el momento en que documentar deja de ser higiene y pasa a tener un consumidor</strong>: lo que se escribió una vez en <code>entidades.md</code> es lo que evita que el agente se invente qué es un cliente aquí.</p>
<p>La lista de <code>include</code> tampoco sobra. Sin ella nao copia el proyecto completo, cuatrocientos noventa y tres ficheros, casi todos de <code>target/</code> y de <code>logs/</code>: el manifiesto, el catálogo y el sitio de documentación ya compilado. Nada de eso ayuda y todo eso ocupa contexto. Con el filtro se queda en cuarenta y nueve.</p>
</section>
<section id="la-documentación-no-viaja-por-un-solo-camino" class="level4">
<h4 class="anchored" data-anchor-id="la-documentación-no-viaja-por-un-solo-camino">La documentación no viaja por un solo camino</h4>
<p>Merece la pena mirar lo que el sync deja escrito, en <code>nao_project/databases/.../table=employee_360/columns.md</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># employee_360</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Description</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>_No description available._</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Y sin embargo esa descripción existe, está en <code>_analytics_models.yml</code>. Lo que pasa es que el proveedor de DuckDB de nao saca el esquema con Ibis, que no trae los comentarios del catálogo. El proyecto los escribe igualmente, porque es lo correcto:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">models</span><span class="kw">:</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">data_vault_odoo</span><span class="kw">:</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">+persist_docs</span><span class="kw">:</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="fu">relation</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="at">      </span><span class="fu">columns</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Con eso, <code>dbt build</code> deja las descripciones dentro de la propia base de datos (<code>COMMENT ON</code>), donde las encuentra cualquier cliente SQL o catálogo sin saber que dbt existe:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> table_name, <span class="kw">comment</span> <span class="kw">FROM</span> duckdb_tables() <span class="kw">WHERE</span> <span class="kw">comment</span> <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span>;</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>A nao esas descripciones le llegan por el otro lado, con el repositorio sincronizado. Son <strong>dos caminos distintos para la misma documentación y ninguna herramienta usa los dos</strong>, que es una buena razón para escribirla una sola vez y publicarla por todos los sitios que se pueda.</p>
</section>
<section id="la-clave-y-lo-que-sale-de-casa" class="level4">
<h4 class="anchored" data-anchor-id="la-clave-y-lo-que-sale-de-casa">La clave y lo que sale de casa</h4>
<p>El agente necesita un modelo, y ahí hay dos cosas que decir.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../assets/nao_chat.png" class="img-fluid figure-img"></p>
<figcaption>Panel de consulta en Nao</figcaption>
</figure>
</div>
<p>La clave llega por variable de entorno y no se versiona:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="bu">export</span> <span class="va">ANTHROPIC_API_KEY</span><span class="op">=</span>sk-...</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose <span class="at">--profile</span> ai up <span class="at">-d</span> nao</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Sin ella la interfaz arranca igual y avisa con un “Configure a model” en el cuadro de texto, que es un modo degradado razonable: se puede mirar el contexto construido sin gastar un céntimo.</p>
<p>Lo segundo es más importante y no lo pregunta nadie. <strong>Un agente analítico manda a un tercero el esquema de tu almacén y muestras de tus filas.</strong> Es inherente a cómo funciona, no un defecto de esta herramienta. Aquí es donde la decisión que tomamos en la ingesta deja de ser teórica: los documentos de identidad y las fechas de nacimiento de <code>hr_employee</code> no salieron nunca del ERP, así que no hay forma de que acaben en una llamada a un modelo. Si hubiéramos hecho un <code>SELECT *</code> porque total ya se filtrará luego, ese “luego” habría llegado justo aquí.</p>
<p>Y una tercera, menor: nao envía telemetría de uso a PostHog por defecto. Son eventos del tipo “mensaje enviado”, no datos del almacén, pero el ejercicio la desactiva de forma explícita con <code>POSTHOG_DISABLED: "true"</code> porque una decisión así se toma, no se descubre.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Con este sí se puede trabajar a la vez
</div>
</div>
<div class="callout-body-container callout-body">
<p>Al contrario que Rill, nao <strong>no impide reconstruir el almacén</strong>. Su proveedor de DuckDB abre el fichero en solo lectura y no mantiene la conexión abierta, de modo que con el chat levantado <code>dbt build</code> funciona con normalidad.</p>
<p>Esto obliga a afinar la regla del bloqueo, que es más sencilla de lo que parecía: DuckDB admite <strong>varios lectores a la vez y un solo escritor</strong>. Con Rill levantado, <code>nao sync</code> entra sin problema (los dos leen) y dbt falla (quiere escribir). Lo que no puede solaparse es la escritura, no la lectura.</p>
</div>
</div>
<p>El estado propio del chat (la cuenta y el historial de conversaciones) vive en un SQLite dentro del contenedor, así que sobrevive a <code>stop</code> y <code>start</code> pero no a <code>down</code>. Para un ejercicio está bien; para algo serio, la imagen admite un PostgreSQL con <code>DB_URI</code>.</p>
</section>
</section>
<section id="comprobar-que-está-todo" class="level3" data-number="E.3.10">
<h3 data-number="E.3.10" class="anchored" data-anchor-id="comprobar-que-está-todo"><span class="header-section-number">E.3.10</span> Comprobar que está todo</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> <span class="at">--entrypoint</span> python transform <span class="at">-c</span> <span class="st">"</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="st">import duckdb</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="st">con = duckdb.connect('/data/warehouse.duckdb', read_only=True)</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="st">print(con.execute('SELECT count(*) FROM vault.hub_customer').fetchone())</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="st">print(con.execute('SELECT * FROM main.kpis_daily LIMIT 5').fetchall())</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="st">print(con.execute('SELECT sum(amount_total) FROM main.point_in_time_orders').fetchone())</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="st">print(con.execute('SELECT sum(price_total) FROM main.point_in_time_order_lines').fetchone())</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Las dos últimas líneas son la comprobación que más veces salva un panel: <strong>tienen que dar lo mismo</strong> (17.670,50). Si no coinciden, algún salto por el vault está multiplicando filas y todo lo que se mida a grano de línea estará inflado.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> transform dbt test</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="lo-que-ha-quedado-construido" class="level2" data-number="E.4">
<h2 data-number="E.4" class="anchored" data-anchor-id="lo-que-ha-quedado-construido"><span class="header-section-number">E.4</span> Lo que ha quedado construido</h2>
<p>Cuatro capas en un mismo fichero DuckDB, cada una en su esquema.</p>
<table class="caption-top table">
<caption>Las capas del almacén y lo que hay en cada una</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Esquema</th>
<th>Capa</th>
<th>Contenido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>raw</code></td>
<td>Bronce</td>
<td>Reflejo de Odoo, sin transformar (10 tablas)</td>
</tr>
<tr class="even">
<td><code>staging</code></td>
<td>Preparación</td>
<td>Vistas que resuelven las rarezas del origen (10 vistas)</td>
</tr>
<tr class="odd">
<td><code>vault</code></td>
<td>Plata</td>
<td>6 hubs, 5 enlaces, 7 satélites y 2 tablas de referencia</td>
</tr>
<tr class="even">
<td><code>main</code></td>
<td>Oro</td>
<td><code>point_in_time_orders</code>, <code>point_in_time_order_lines</code>, <code>kpis_daily</code>, <code>customer_360</code>, <code>customer_history</code>, <code>employee_360</code>, <code>product_performance</code></td>
</tr>
<tr class="odd">
<td><code>meta</code></td>
<td>Metadatos</td>
<td>Qué hay, quién lo vigila y en qué estado: <code>activos</code>, <code>controles</code>, <code>frescura</code>, <code>perfil</code>, <code>perfil_historico</code> y la vista <code>veredicto</code></td>
</tr>
</tbody>
</table>
<p><code>meta</code> no es una quinta capa del dato, es una capa <strong>sobre</strong> el dato: no la produce ninguna transformación sino la consolidación de lo que dejaron dbt y Soda. Vive dentro del mismo fichero a propósito, porque el proceso que quiera saber si puede fiarse de una tabla va a lanzar una consulta, no a abrir una interfaz.</p>
<p>Los dos consumidores finales no ven lo mismo, y no por casualidad. Rill ataca tres tablas de <code>main</code> a través de su capa semántica, más el puente de metadatos para su panel de calidad. El agente de nao ve las siete de <code>main</code> y las seis de <code>meta</code>, y ninguna más: puede comprobar si la tabla con la que va a contestar está vigilada y en verde, que es lo que le permite saber cuándo no fiarse de sí mismo.</p>
<p>Ninguno de los dos llega al vault ni a <code>raw</code>. La capa oro es la frontera, y por debajo de ella el almacén es asunto de dbt.</p>
<p>El vault entero, con las entidades nuevas y las relaciones que las unen:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    hc(("Cliente")) --- loc[["Pedido&lt;br/&gt;Cliente"]]
    loc --- ho(("Pedido"))
    ho --- lop[["Pedido&lt;br/&gt;Producto"]]
    lop --- hp(("Producto"))
    ho --- loe[["Pedido&lt;br/&gt;Empleado"]]
    loe --- he(("Empleado"))
    he --- led[["Empleado&lt;br/&gt;Departamento"]]
    led --- hd(("Departamento"))
    hp --- lpc[["Producto&lt;br/&gt;Categoría"]]
    lpc --- hcat(("Categoría"))

    classDef hub fill:#d5e6f5,stroke:#3d7cb0,stroke-width:1.5px,color:#12354e
    classDef enlace fill:#fae3c8,stroke:#bf7f28,stroke-width:1.5px,color:#573809
    class hc,ho,hp,he,hd,hcat hub
    class loc,lop,loe,led,lpc enlace
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Los círculos son hubs (claves de negocio) y los rectángulos, enlaces (relaciones). Los satélites no se dibujan para no emborronarlo: cuelgan de casi todos ellos y son los que guardan los atributos y su historia. Las dos tablas de referencia (<code>ref_country</code> y <code>ref_sales_team</code>) tampoco aparecen, porque no se relacionan con nada: se consultan al final, para traducir códigos.</p>
<p>Que la capa de explotación viva en <code>main</code> y no en un esquema propio llamado <code>analytics</code> no es un descuido. Rill solo sabe direccionar tablas del esquema por defecto de la base de datos que adjunta (sus claves <code>database</code> y <code>database_schema</code> se ignoran con este conector), de modo que una tabla en un esquema <code>analytics</code> resulta invisible para el panel. Las capas de abajo sí van en su esquema porque solo las consume dbt. Es un ejemplo pequeño y muy típico de cómo una limitación de la herramienta de consumo acaba decidiendo dónde se materializa el dato.</p>
</section>
<section id="las-decisiones-que-importan" class="level2" data-number="E.5">
<h2 data-number="E.5" class="anchored" data-anchor-id="las-decisiones-que-importan"><span class="header-section-number">E.5</span> Las decisiones que importan</h2>
<p>Ocho cosas de este montaje merecen explicación, porque son las que separan un Data Vault que funciona de uno que parece funcionar.</p>
<section id="el-hub-se-carga-desde-todos-los-orígenes" class="level3" data-number="E.5.1">
<h3 data-number="E.5.1" class="anchored" data-anchor-id="el-hub-se-carga-desde-todos-los-orígenes"><span class="header-section-number">E.5.1</span> El hub se carga desde todos los orígenes</h3>
<p>Un hub guarda claves de negocio. La tentación es sacarlas de la tabla que “es” esa entidad (los clientes, de la tabla de clientes) y ya está. Pero un pedido también nombra a un cliente, y si esa clave no estaba en la lista de contactos que hemos filtrado, el enlace apunta a un hub donde no existe y <strong>el vault queda roto</strong>.</p>
<p>Aquí <code>hub_customer</code> se carga de dos sitios a la vez:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> fuente <span class="kw">AS</span> (</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> customer_id <span class="kw">FROM</span> {{ <span class="fu">ref</span>(<span class="st">'stg_customers'</span>) }}</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> customer_id <span class="kw">FROM</span> {{ <span class="fu">ref</span>(<span class="st">'stg_orders'</span>) }}</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Esto no es una precaución teórica. Al construir el ejercicio, el filtro <code>customer_rank &gt; 0</code> en staging dejaba fuera a los tres clientes que tienen pedidos, y la prueba <code>relationships</code> del enlace saltó con quince filas huérfanas. La razón es de las que solo se aprenden mirando: Odoo incrementa ese contador desde el flujo de su interfaz, no desde la base de datos, así que los datos de demostración (que se cargan como fixtures XML) lo dejan a cero incluso para quien tiene pedidos confirmados.</p>
<p>De ahí la regla, que conviene llevarse escrita: <strong>un filtro de negocio no puede decidir qué claves existen</strong>.</p>
</section>
<section id="los-satélites-no-se-cierran-se-deducen" class="level3" data-number="E.5.2">
<h3 data-number="E.5.2" class="anchored" data-anchor-id="los-satélites-no-se-cierran-se-deducen"><span class="header-section-number">E.5.2</span> Los satélites no se cierran, se deducen</h3>
<p>Casi toda la literatura describe el satélite con una columna <code>dv_end_date</code> que se rellena cuando el atributo cambia, y con <code>NULL</code> para la versión vigente. Es fácil de explicar y es una mala idea de implementar, porque cerrar una fila exige un <code>UPDATE</code> sobre el histórico, que es justo lo que un vault no debe hacer nunca.</p>
<p>Aquí los satélites son de <strong>solo inserción</strong>. En cada carga se calcula la huella (<code>hashdiff</code>) de los atributos y solo se escribe si difiere de la última guardada para esa clave. La vigencia y el intervalo de validez se calculan al consultar, con una función de ventana:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lead</span>(s.load_date) <span class="kw">OVER</span> (</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">PARTITION</span> <span class="kw">BY</span> s.hk_customer</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ORDER</span> <span class="kw">BY</span> s.load_date</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>) <span class="kw">AS</span> dv_end_date</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Si hay una carga posterior, esa es la fecha en la que la versión dejó de ser cierta. Si no la hay, la versión sigue vigente y el cierre queda a <code>NULL</code>. El resultado es el mismo que promete la teoría, y el histórico no se toca jamás. Está en el modelo <code>customer_history</code>.</p>
</section>
<section id="el-enlace-no-lleva-atributos" class="level3" data-number="E.5.3">
<h3 data-number="E.5.3" class="anchored" data-anchor-id="el-enlace-no-lleva-atributos"><span class="header-section-number">E.5.3</span> El enlace no lleva atributos</h3>
<p>Un enlace guarda la relación y las claves de los hubs que une. Nada más. Meter la cantidad de la línea dentro del enlace pedido-producto, que es lo primero que uno hace, rompe por dos sitios: un mismo producto puede aparecer en dos líneas del mismo pedido (con lo que el par deja de ser único) y la cantidad es un atributo descriptivo, que en Data Vault va siempre en un satélite.</p>
<p>La solución del ejercicio es tomar la línea de pedido como grano del enlace, conservar su identificador como clave degenerada y colgar del enlace un satélite (<code>sat_order_line</code>) con cantidades y precios.</p>
</section>
<section id="lo-que-parece-un-atributo-y-es-una-entidad" class="level3" data-number="E.5.4">
<h3 data-number="E.5.4" class="anchored" data-anchor-id="lo-que-parece-un-atributo-y-es-una-entidad"><span class="header-section-number">E.5.4</span> Lo que parece un atributo y es una entidad</h3>
<p>Al entrar los módulos nuevos aparece la decisión que más veces se toma mal, y hay que tomarla tres veces seguidas: el departamento del empleado, la categoría del producto y el equipo del pedido son, los tres, una columna con un número que apunta a otra tabla. La pregunta es si esa columna se queda dentro del satélite o se convierte en un hub con su enlace.</p>
<p>La respuesta no es “siempre hub”. Depende de si la cosa referida <strong>tiene identidad propia y atributos que interese historiar</strong>:</p>
<ul>
<li><strong>El departamento sí.</strong> Tiene nombre, responsable y posición en un organigrama, y todo eso cambia. Va a <code>hub_department</code> con su satélite, y la adscripción del empleado a <code>link_employee_department</code>.</li>
<li><strong>La categoría también.</strong> Y aquí se ve mejor la consecuencia de equivocarse: con <code>categ_id</code> metido en el satélite del producto, renombrar una categoría escribiría una versión nueva en los cientos de productos que cuelgan de ella, como si todos hubiesen cambiado.</li>
<li><strong>El puesto (<code>job_title</code>) no.</strong> Llega como texto libre en la ficha del empleado, no referencia a ninguna tabla y nadie va a preguntar por la historia de un puesto. Se queda como atributo.</li>
<li><strong>El equipo comercial, tampoco, pero por otra razón.</strong> Es una entidad de verdad, con responsable y objetivos. Lo que pasa es que en este almacén solo aparece para que el <code>team_id</code> del pedido se lea como “Pre-Sales”, y para eso basta una <strong>tabla de referencia</strong>.</li>
</ul>
<p>Ese tercer tipo de tabla del Data Vault es el que menos se explica. No lleva clave hash, no lleva satélite y no es de solo inserción: se reconstruye entera en cada carga. <code>ref_country</code> es el ejemplo de manual (doscientas cincuenta filas que no cambian casi nunca y existen para que <code>country_id = 233</code> se lea como “United States”), y <code>ref_sales_team</code> es el caso discutible, puesto ahí a propósito para que se vea dónde está la frontera.</p>
<p>La regla no es sobre la entidad, es sobre el uso: <strong>una tabla de referencia es una entidad de la que no queremos historia</strong>. Lo que se renuncia al elegirla es justo eso: si un país cambia de nombre, el nombre viejo desaparece del almacén y los informes de hace tres años se redibujan con el nombre nuevo. Para países es asumible; para una tabla de tarifas sería un desastre, y ahí la decisión correcta es la contraria.</p>
</section>
<section id="los-enlaces-también-tienen-versión-vigente" class="level3" data-number="E.5.5">
<h3 data-number="E.5.5" class="anchored" data-anchor-id="los-enlaces-también-tienen-versión-vigente"><span class="header-section-number">E.5.5</span> Los enlaces también tienen versión vigente</h3>
<p>Esta es la trampa que aparece en cuanto un enlace deja de ser inmutable, y cuesta verla porque no rompe nada: solo cambia los números.</p>
<p>Los satélites eran de solo inserción y ya sabíamos deducir su versión vigente. Los enlaces también lo son, y eso significa que <strong>cuando una relación cambia no se sustituye nada</strong>. Si un empleado se traslada de departamento, el enlace pasa a tener dos filas para esa persona, una por cada departamento, y las dos son ciertas. Al consultarlo sin más, ese empleado sale dos veces, y una plantilla de veinte personas aparece como veintiuna en el panel.</p>
<p>La solución no es cerrar filas, que es lo que un vault no hace, sino declarar cuál es la <strong>clave conductora</strong> (<em>driving key</em>) de la relación: el extremo que se mueve. En el traslado se mueve el empleado, no el departamento. Quedándose con su carga más reciente sale la relación vigente:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>{% macro enlace_vigente(relacion, clave_conductora) <span class="op">-</span>%}</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="op">*</span> EXCLUDE (dv_fila)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> (</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>        <span class="kw">SELECT</span> <span class="op">*</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">row_number</span>() <span class="kw">OVER</span> (<span class="kw">PARTITION</span> <span class="kw">BY</span> {{ clave_conductora }}</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>                               <span class="kw">ORDER</span> <span class="kw">BY</span> load_date <span class="kw">DESC</span>) <span class="kw">AS</span> dv_fila</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> {{ relacion }}</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">WHERE</span> dv_fila <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>{%<span class="op">-</span> endmacro %}</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Es la misma idea que <code>satelite_vigente()</code> aplicada a un sitio donde casi nadie la aplica. Lo que esta macro no cubre conviene tenerlo presente: si la relación <strong>desaparece</strong> del origen, la última fila escrita sigue siendo la antigua y aquí se dará por vigente. Distinguir “sigue igual” de “ya no está” exige un satélite de efectividad del enlace, y este proyecto no lo monta.</p>
<p>La prueba que protege de todo esto no está en el vault sino en la capa oro, y es de las más aburridas que existen: <code>employee_360.employee_id</code> tiene que ser única. Si alguien consulta el enlace olvidando la clave conductora, esa unicidad se rompe y la carga se para antes de que nadie mire un número inflado.</p>
</section>
<section id="dos-identidades-para-la-misma-persona" class="level3" data-number="E.5.6">
<h3 data-number="E.5.6" class="anchored" data-anchor-id="dos-identidades-para-la-misma-persona"><span class="header-section-number">E.5.6</span> Dos identidades para la misma persona</h3>
<p>El pedido dice quién es el comercial con un <code>user_id</code>, que es una <strong>cuenta de Odoo</strong> (<code>res_users</code>). La plantilla vive en <code>hr_employee</code>, que apunta a su cuenta con otro <code>user_id</code> propio. Son dos identificadores distintos de la misma persona, y no hay ninguna columna que los case: hay que ir por el único sitio donde coinciden.</p>
<p>Elegir mal la clave de negocio del hub aquí se paga a la vista: montado sobre la cuenta de usuario, <code>hub_employee</code> se quedaría con dos de veinte empleados, porque la mayoría de la plantilla no tiene cuenta en el ERP.</p>
<p>La traducción se hace una sola vez, en <code>stg_order_salesperson</code>, y esa es la parte que importa. Si viviera dentro del enlace del vault, cada modelo que necesitase al comercial tendría que repetirla, y bastaría con que dos la resolvieran distinto para que el almacén contase dos historias. El <code>INNER JOIN</code> de ese modelo deja fuera los pedidos cuyo comercial no es empleado (un usuario del portal, una cuenta de integración), que es lo seguro, y una prueba con <code>severity: warn</code> avisa de cuántos se quedan por el camino sin romper la carga:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>{{ config(severity <span class="op">=</span> <span class="st">'warn'</span>) }}</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>La distinción entre avisar y fallar es una decisión de diseño, no un descuido. Que un pedido lo firme una cuenta sin ficha de empleado es una situación legítima del origen, así que parar la carga por eso sería castigar al almacén por algo que pasa en el ERP. Lo que no puede ocurrir es que pase en silencio: el día que alguien cambie la cuenta de un comercial, sus pedidos desaparecerían del panel de rendimiento sin que ninguna carga fallase.</p>
</section>
<section id="el-grano-manda" class="level3" data-number="E.5.7">
<h3 data-number="E.5.7" class="anchored" data-anchor-id="el-grano-manda"><span class="header-section-number">E.5.7</span> El grano manda</h3>
<p><code>point_in_time_orders</code> tiene una fila por pedido y <code>point_in_time_order_lines</code> una por línea. Las dos traen facturación y las dos son correctas, pero <strong>no son la misma facturación</strong>, y mezclarlas es la forma más común de que un panel dé números que no cuadran.</p>
<p>A grano de pedido, <code>sum(amount_total)</code> es la facturación. A grano de línea, la misma suma la multiplica por el número de líneas de cada pedido: en este almacén, quince pedidos y treinta y tres líneas convertirían 17.670,50 euros en bastante más. Por eso la vista de línea no arrastra el importe de la cabecera, sino que suma <code>price_total</code>, y cuenta pedidos con <code>count(distinct order_id)</code>.</p>
<p>La comprobación que conviene tener a mano es que las dos sumas coincidan cuando no hay filtro, y en este almacén coinciden. En cuanto se filtra por producto dejan de hacerlo, y es correcto que así sea: un producto no es responsable del pedido entero.</p>
<p>Lo mismo pasa en la capa semántica, y ahí queda mejor resuelto: <code>ventas.yaml</code> y <code>catalogo.yaml</code> son dos vistas de métricas distintas precisamente porque atacan granos distintos, y eso hace imposible pedirle a Rill una combinación que no existe.</p>
</section>
<section id="el-modelo-físico-de-un-erp-no-es-el-que-enseña" class="level3" data-number="E.5.8">
<h3 data-number="E.5.8" class="anchored" data-anchor-id="el-modelo-físico-de-un-erp-no-es-el-que-enseña"><span class="header-section-number">E.5.8</span> El modelo físico de un ERP no es el que enseña</h3>
<p>Esta es la lección que justifica usar Odoo en lugar de un origen de juguete. Lo que la interfaz presenta como un producto con su nombre y su precio, por debajo es otra cosa:</p>
<ul>
<li><strong><code>product_product</code> no tiene nombre ni precio.</strong> Son campos de la plantilla (<code>product_template</code>), y hay que ir a buscarlos con un <code>join</code>.</li>
<li><strong><code>product_template.name</code> es <code>jsonb</code></strong>, porque desde Odoo 16 los campos traducibles se guardan como un diccionario de idiomas. Hay que extraerlo con <code>json_extract_string(name, '$.en_US')</code>.</li>
<li><strong><code>standard_price</code> no existe como columna.</strong> Vive en <code>ir_property</code>, porque depende de la compañía. Cualquier cálculo de margen tiene que ir allí.</li>
</ul>
<p>Con los módulos nuevos aparece una cuarta, y es la más traicionera porque parece una regla y no lo es. Uno aprende que en Odoo 16 los nombres son JSON y lo aplica a todo. Pues no:</p>
<table class="caption-top table">
<caption>El mismo nombre de columna, cuatro veces JSON y tres veces texto</caption>
<thead>
<tr class="header">
<th>Tabla</th>
<th>Tipo de <code>name</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>product_template</code></td>
<td><code>jsonb</code></td>
</tr>
<tr class="even">
<td><code>hr_job</code></td>
<td><code>jsonb</code></td>
</tr>
<tr class="odd">
<td><code>crm_team</code></td>
<td><code>jsonb</code></td>
</tr>
<tr class="even">
<td><code>res_country</code></td>
<td><code>jsonb</code></td>
</tr>
<tr class="odd">
<td><code>hr_department</code></td>
<td><code>varchar</code></td>
</tr>
<tr class="even">
<td><code>product_category</code></td>
<td><code>varchar</code></td>
</tr>
<tr class="odd">
<td><code>hr_employee</code></td>
<td><code>varchar</code></td>
</tr>
</tbody>
</table>
<p>La diferencia la decide cada modelo de Odoo al declarar el campo como traducible o no, así que <strong>no hay una regla que aplicar a ciegas</strong>: hay que mirar <code>information_schema</code> tabla por tabla. Descubrirlo tarde significa un <code>json_extract_string</code> sobre una columna de texto, que en DuckDB no falla con un error claro sino que devuelve <code>NULL</code>, y un panel lleno de huecos es mucho más difícil de diagnosticar que una consulta que se rompe.</p>
<p>Hay una quinta rareza que solo se ve mirando los datos y no el esquema: en el catálogo de demostración <strong>hay dos categorías distintas llamadas “Saleable”</strong>, una colgando de “All” y otra de “All / Saleable / Services”. Agrupar por el nombre corto en un panel mezclaría dos cosas que no son la misma, así que lo que se usa para agrupar es la ruta completa. Ningún tipo de dato ni ninguna restricción de la base de datos avisa de esto.</p>
<p>Todo esto se resuelve en la capa de staging, que es exactamente para lo que sirve: <strong>absorber la rareza del origen una sola vez</strong> para que no se propague al resto.</p>
</section>
</section>
<section id="ejercicios" class="level2" data-number="E.6">
<h2 data-number="E.6" class="anchored" data-anchor-id="ejercicios"><span class="header-section-number">E.6</span> Ejercicios</h2>
<section id="ver-el-historial-en-funcionamiento" class="level3" data-number="E.6.1">
<h3 data-number="E.6.1" class="anchored" data-anchor-id="ver-el-historial-en-funcionamiento"><span class="header-section-number">E.6.1</span> Ver el historial en funcionamiento</h3>
<p>Con una sola carga cada cliente tiene una única versión y el histórico no se aprecia. Hay que cambiar algo y volver a pasar el pipeline:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> exec dl-postgres psql <span class="at">-U</span> odoo <span class="at">-d</span> odoo_demo <span class="dt">\</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">-c</span> <span class="st">"UPDATE res_partner SET city='Bilbao' WHERE id=11;"</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose stop rill</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> extract</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> transform</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El satélite pasa de cuarenta filas a cuarenta y una (no a ochenta: solo se escribe lo que cambió) y <code>customer_history</code> muestra la versión antigua cerrada con la fecha de la carga nueva y la nueva abierta. La consulta:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> customer_name, city, dv_start_date, dv_end_date, es_version_vigente</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> main.customer_history <span class="kw">WHERE</span> customer_id <span class="op">=</span> <span class="dv">11</span> <span class="kw">ORDER</span> <span class="kw">BY</span> dv_start_date;</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Conviene ejecutar <code>transform</code> una tercera vez sin tocar nada y comprobar que <strong>no aparece ninguna fila nueva</strong>. Si aparece, la detección por huella está mal y el histórico se llenaría de duplicados a cada carga.</p>
</section>
<section id="romper-la-integridad-a-propósito" class="level3" data-number="E.6.2">
<h3 data-number="E.6.2" class="anchored" data-anchor-id="romper-la-integridad-a-propósito"><span class="header-section-number">E.6.2</span> Romper la integridad a propósito</h3>
<p>Merece la pena ver fallar la prueba que protege el vault, y el ejercicio enseña más de lo que parece porque <strong>hacen falta dos cambios, no uno</strong>.</p>
<p>El primero es el filtro que parecía inofensivo, en <code>stg_customers.sql</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> <span class="kw">id</span> <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> customer_rank <span class="op">&gt;</span> <span class="dv">0</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Con eso solo, todo sigue pasando. El hub se carga de dos orígenes, así que las claves que el filtro deja fuera entran igualmente por la puerta de los pedidos. Para romperlo hay que quitar además esa segunda fuente en <code>hub_customer.sql</code>, dejando el hub alimentado únicamente por la lista de contactos:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> fuente <span class="kw">AS</span> (</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">DISTINCT</span> customer_id <span class="kw">FROM</span> {{ <span class="fu">ref</span>(<span class="st">'stg_customers'</span>) }}</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>),</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Y hay un tercer detalle. Los hubs son de solo inserción, de modo que las claves cargadas en ejecuciones anteriores siguen ahí y tapan el problema. Hay que reconstruir desde cero:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> transform dbt build <span class="at">--full-refresh</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Ahora sí: <code>Got 15 results</code>, la prueba <code>relationships</code> del enlace falla y el proceso termina con código distinto de cero. Esas quince filas son pedidos que apuntan a un cliente que no existe en el hub.</p>
<p>La conclusión es la que interesa: el filtro por sí solo no era el fallo, y la carga multiorigen del hub no era una precaución decorativa. Cada uno tapaba al otro, y solo quitando los dos aparece el problema. Para volver atrás, basta con deshacer ambos cambios y repetir el <code>--full-refresh</code>.</p>
</section>
<section id="trasladar-a-alguien-de-departamento" class="level3" data-number="E.6.3">
<h3 data-number="E.6.3" class="anchored" data-anchor-id="trasladar-a-alguien-de-departamento"><span class="header-section-number">E.6.3</span> Trasladar a alguien de departamento</h3>
<p>Es el ejercicio que enseña la clave conductora, y se hace en una orden:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> exec dl-postgres psql <span class="at">-U</span> odoo <span class="at">-d</span> odoo_demo <span class="dt">\</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">-c</span> <span class="st">"UPDATE hr_employee SET department_id=2 WHERE id=7;"</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose stop rill</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> extract</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose run <span class="at">--rm</span> transform</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Marc Demo pasa de Investigación y Desarrollo a Ventas. Lo que hay que mirar después son tres recuentos, y cada uno dice algo distinto:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="op">*</span>) <span class="kw">FROM</span> vault.link_employee_department;  <span class="co">-- 20 -&gt; 21</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="op">*</span>) <span class="kw">FROM</span> vault.sat_employee_details;      <span class="co">-- 20 -&gt; 20</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="op">*</span>) <span class="kw">FROM</span> main.employee_360;               <span class="co">-- 20 -&gt; 20</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El enlace crece porque la relación nueva se añade sin borrar la vieja. <strong>El satélite no se mueve</strong>, y esa es la comprobación de que el diseño era el correcto: como el departamento no es un atributo del empleado, un traslado no ensucia su ficha. Y la capa oro sigue con veinte filas porque <code>enlace_vigente()</code> se queda con la última adscripción; si se quita esa macro del modelo, la prueba de unicidad de <code>employee_360</code> falla y la carga se para, que es exactamente lo que tenía que pasar.</p>
<p>En el enlace quedan las dos adscripciones con su fecha, así que la pregunta “¿en qué departamento estaba cuando firmó aquel pedido?” tiene respuesta. Contestarla es el siguiente ejercicio.</p>
</section>
<section id="modelar-la-jerarquía-como-enlace" class="level3" data-number="E.6.4">
<h3 data-number="E.6.4" class="anchored" data-anchor-id="modelar-la-jerarquía-como-enlace"><span class="header-section-number">E.6.4</span> Modelar la jerarquía como enlace</h3>
<p>Los departamentos y las categorías son árboles, y este proyecto se salta el problema: guarda <code>parent_id</code> y la ruta ya calculada (<code>department_path</code>) como atributos del satélite, porque el origen las da hechas.</p>
<p>La forma estricta es un <strong>enlace jerárquico</strong>, un enlace cuyos dos extremos apuntan al mismo hub (<code>link_department_hierarchy</code>, con <code>hk_department_hijo</code> y <code>hk_department_padre</code>). Montarlo obliga a resolver dos cosas que el atajo esconde: cómo se consulta la ruta completa sin la columna precalculada (con un <code>WITH RECURSIVE</code>) y qué pasa con la raíz, que no tiene padre. Merece la pena hacerlo con las categorías, que son solo nueve.</p>
</section>
<section id="añadir-un-origen" class="level3" data-number="E.6.5">
<h3 data-number="E.6.5" class="anchored" data-anchor-id="añadir-un-origen"><span class="header-section-number">E.6.5</span> Añadir un origen</h3>
<p>Odoo tiene facturas (<code>account_move</code> y <code>account_move_line</code>). Añadirlas es el recorrido completo: declararlas en <code>ODOO_TABLES</code> del pipeline, crear su modelo de staging, decidir si la factura es un hub nuevo o un satélite del pedido (pista: tiene identidad y vida propias) y llevarla hasta la capa de explotación.</p>
</section>
<section id="comprobar-al-agente" class="level3" data-number="E.6.6">
<h3 data-number="E.6.6" class="anchored" data-anchor-id="comprobar-al-agente"><span class="header-section-number">E.6.6</span> Comprobar al agente</h3>
<p>Los agentes analíticos se prueban mal a ojo, porque contestan siempre y con aplomo. La forma útil de evaluarlo es preguntarle algo cuya respuesta ya conocemos por otro camino:</p>
<blockquote class="blockquote">
<p>¿Cuánto facturamos en total y cuántos pedidos hubo?</p>
</blockquote>
<p>Tiene que decir 17.670,50 y 15, que es lo que enseña el panel de Rill. Después conviene subir la dificultad hacia las preguntas donde el modelo importa:</p>
<blockquote class="blockquote">
<p>¿Qué comercial vendió más y de qué departamento es?</p>
</blockquote>
<blockquote class="blockquote">
<p>¿Qué productos del catálogo no se han vendido nunca?</p>
</blockquote>
<p>La segunda es la interesante, porque solo se puede contestar desde <code>product_performance</code>: quien parta de las líneas de pedido no puede ver lo que no se vendió. Si el agente responde bien a esa, es que está usando el modelo y no improvisando SQL.</p>
<p>El ejercicio de verdad viene después: quitar el <code>include</code> de <code>nao_config.yaml</code> para que vea también <code>raw</code>, volver a sincronizar y repetir las mismas preguntas. Las respuestas empeoran de una forma muy concreta, contando presupuestos como pedidos, y se entiende de golpe para qué servían las capas intermedias.</p>
</section>
<section id="calcular-el-margen" class="level3" data-number="E.6.7">
<h3 data-number="E.6.7" class="anchored" data-anchor-id="calcular-el-margen"><span class="header-section-number">E.6.7</span> Calcular el margen</h3>
<p><code>product_performance</code> mide facturación, unidades y descuento, y no dice nada de rentabilidad. No es un olvido: el coste (<code>standard_price</code>) no es una columna en Odoo, vive en <code>ir_property</code> porque depende de la compañía, y ahí está guardado como texto junto con propiedades de cualquier otro modelo.</p>
<p>Traerlo obliga a lo que ninguna tabla limpia enseña: filtrar <code>ir_property</code> por el campo que corresponde a <code>standard_price</code>, quedarse con la propiedad de la compañía adecuada, convertir el valor y decidir qué hacer con los productos que no la tienen. Es el ejercicio que más se parece al trabajo real de este oficio.</p>
</section>
</section>
<section id="lo-que-hay-que-vigilar" class="level2" data-number="E.7">
<h2 data-number="E.7" class="anchored" data-anchor-id="lo-que-hay-que-vigilar"><span class="header-section-number">E.7</span> Lo que hay que vigilar</h2>
<p><strong>Las versiones de dbt y su adaptador tienen que ir emparejadas.</strong> Si se instala <code>dbt-duckdb</code> sin fijar también <code>dbt-core</code>, pip resuelve el núcleo más nuevo que exista y lo empareja con un adaptador viejo. Esa combinación arranca, avisa de que el plugin está desactualizado y luego <strong>se cae de forma intermitente</strong>, que es la peor manera de fallar. Las versiones van fijadas en <code>docker/toolbox.Dockerfile</code>.</p>
<p><strong>DuckDB escribe con un solo proceso.</strong> Admite varios lectores a la vez, pero un único escritor: es la regla que explica por qué nao convive con Rill y dbt no. Además, el proyecto usa un único hilo de dbt (<code>threads: 1</code>). Subirlo no acelera nada y provoca caídas cuando varios modelos escriben a la vez.</p>
<p><strong>Soda obliga a un duckdb más viejo, así que va en imagen aparte.</strong> <code>soda-core-duckdb</code> declara <code>duckdb&lt;1.1.0</code>. Instalarlo junto a dbt degradaría el motor que escribe el almacén de 1.1.3 a 1.0.0 sin decir nada, que es la misma clase de accidente que la del adaptador de dbt. Por eso hay un <code>docker/soda.Dockerfile</code> propio. Que puedan convivir con versiones distintas no es suerte: el formato de almacenamiento de DuckDB es estable dentro de la serie 1.x, y conviene volver a comprobarlo al subir cualquiera de las dos.</p>
<p><strong>Y necesita <code>pytz</code>, que no pide él.</strong> Lo pide el cliente de DuckDB, y solo al tocar una columna <code>TIMESTAMP WITH TIME ZONE</code>, que en este proyecto es la primera comprobación de frescura. El error tampoco ayuda: se ve un <code>cannot rollback - no transaction is active</code> con una traza larga de Soda, y el motivo real (<code>Required module 'pytz' failed to import</code>) aparece tres líneas más abajo.</p>
<p><strong>nao también va emparejado consigo mismo.</strong> La CLI que construye el contexto (<code>nao-core</code>, en la imagen de utilidades) y el contenedor del chat tienen que ser de la misma versión, por el mismo motivo que dbt y su adaptador. Es un proyecto joven que solo publica etiquetas por commit, así que fijar la versión obliga a escribir el hash (<code>getnao/nao:b325bba</code>, la 0.3.3). Con <code>latest</code> bastaría con que cambiaran el formato del contexto para que el ya construido dejara de leerse.</p>
<p><strong><code>pyarrow-hotfix</code> hace falta y no lo pide nadie.</strong> La versión de duckdb del proyecto lo importa siempre que convierte un resultado a Arrow, aunque el parche solo fuera necesario para pyarrow anterior al 14. Sin ese paquete, <code>nao sync</code> conecta, encuentra las tablas, falla en todas con un <code>No module named 'pyarrow_hotfix'</code> y aun así termina imprimiendo <code>7 tables synced</code> en verde. El contexto queda vacío y nada avisa.</p>
<p><strong>El directorio <code>warehouse/</code> tiene que existir antes del primer arranque.</strong> Si no está, Docker lo crea como <code>root</code> y los contenedores, que corren con el usuario del anfitrión, no pueden escribir. En el repositorio va un <code>.gitkeep</code> para que exista siempre.</p>
</section>
<section id="lo-que-este-ejercicio-deja-fuera" class="level2" data-number="E.8">
<h2 data-number="E.8" class="anchored" data-anchor-id="lo-que-este-ejercicio-deja-fuera"><span class="header-section-number">E.8</span> Lo que este ejercicio deja fuera</h2>
<p>Por mantenerlo reproducible en un portátil, tres piezas se han quedado a la puerta.</p>
<p><strong>El catálogo.</strong> OpenMetadata pide alrededor de 6 GiB solo para él y ya tiene su propio <a href="../../content/appendices/metadatado.html">apéndice</a>, con su despliegue y su puerto. Conectarlo a este almacén es un buen ejercicio adicional. Lo que queda montado cubre una parte de eso y por dos caminos distintos: dbt docs pone el linaje y el diccionario de los modelos, y el esquema <code>meta</code> pone el estado de la vigilancia. Lo que sigue faltando es el glosario de negocio, los propietarios (cada control debería tener un nombre de persona detrás, y aquí no lo tiene) y los tramos que hacen dlt, Rill y nao, que ninguna de las dos piezas ve.</p>
<p><strong>La orquestación.</strong> Aquí el pipeline son dos órdenes seguidas que se lanzan a mano, y para un único origen eso no pide orquestador ninguno: dlt sabe ejecutar un proyecto dbt por su cuenta (<code>dlt.dbt.package</code>), con lo que las dos órdenes se convierten en un script y la dependencia queda expresada por el propio flujo del programa. La maquinaria empieza a compensar cuando los orígenes son varios y hay que esperar a todos. Ambas cosas están en el <a href="../../content/load/herramientas.html#quién-lo-pone-en-marcha">capítulo de herramientas de ingesta</a>.</p>
<p><strong>Los datos.</strong> Esta es la limitación que más se nota al abrir los paneles y no tiene arreglo desde el código: los datos de demostración de Odoo son quince pedidos, dos comerciales y dos categorías con ventas. El modelo soporta mucho más, pero lo que se ve en pantalla son cifras pequeñas. Inventarse volumen habría sido fácil y habría estropeado lo único que justifica usar un ERP real como origen, que es que sus rarezas son las de verdad. Lo que se enseña aquí es el recorrido, no el volumen.</p>
<p><strong>La exploración de verdad.</strong> Quedan tres vistas de métricas, tres paneles de exploración y un <code>canvas</code>, que ya es un proyecto de Rill con forma, pero se queda en la superficie de lo que la herramienta hace. Cómo se le saca partido está en su <a href="../../content/appendices/rill.html">apéndice</a>.</p>
</section>
<section id="desmontarlo" class="level2" data-number="E.9">
<h2 data-number="E.9" class="anchored" data-anchor-id="desmontarlo"><span class="header-section-number">E.9</span> Desmontarlo</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose <span class="at">--profile</span> bi <span class="at">--profile</span> docs <span class="at">--profile</span> jobs <span class="at">--profile</span> ai down <span class="at">-v</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span> <span class="at">-rf</span> warehouse/warehouse.duckdb warehouse/soda_results.json <span class="dt">\</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>       nao_project/databases nao_project/repos</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El <code>-v</code> borra también los volúmenes, es decir, la base de datos de Odoo. Sin él, el ERP conserva sus datos y volver a levantarlo es inmediato. Lo que se borra a mano son artefactos generados: el almacén y el contexto del agente se reconstruyen con las mismas órdenes de siempre.</p>
<p>Las imágenes se quedan, y son unos 7 GiB. Para recuperar el espacio de la más grande:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> rmi getnao/nao:b325bba</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/iraitzm\.github\.io\/ingenieria-datos\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../content/appendices/rill.html" class="pagination-link" aria-label="Exploración con Rill">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Exploración con Rill</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../content/appendices/de_storybook.html" class="pagination-link" aria-label="La danza del Ingeniero de Datos">
        <span class="nav-page-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">La danza del Ingeniero de Datos</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Iraitz Montalbán</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/IraitzM">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/iraitzmontalban/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>